# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Was updated')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Was created')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
